apiVersion: apps/v1
kind: Deployment
metadata:
  name: rbk
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: rbk
  template:
    metadata:
      name: rbk
      labels:
        app: rbk
    spec:
      containers:
        - name: rbk
          env:
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_user
            - name: POSTGRES_PASSWORD
              valueFrom:
                configMapKeyRef:
                  name: postgres-config
                  key: postgres_password
          image: rbk-0.1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8081
              name: rbk
---
apiVersion: v1
kind: Service
metadata:
  name: rbk
spec:
  ports:
    - port: 8081
      targetPort: 8081
  selector:
    app: rbk
  type: LoadBalancer