version: '3'
services:
  rbk:
    build:
      context: ./rbk
    image: "rbk-0.1.0"
    ports:
      - "8081:8081"
    depends_on:
      - dbpostgresql

  darksky:
    build:
      context: ./temperature
    image: "temperature-0.1.0"
    ports:
      - "8082:8082"

  prediction:
    build:
      context: ./prediction
    image: "prediction-0.1.0"
    ports:
      - "8083:8083"

  dbpostgresql:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pas

  prometheus:
    image: prom/prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: grafana/grafana
    ports:
      - "3000:3000"

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@mydomain.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    depends_on:
      - dbpostgresql
