version: '3'
services:
  rbk:
    build:
      context: ./rbk
    image: "rbk-0.1.0"
    ports:
      - "8081:8081"

  darksky:
    build:
      context: ./temperature
    image: "temperature-0.1.0"
    ports:
      - "8082:8082"

  prediction:
    build:
      context: ./prediction
    image: "prediction-0.1.0"
    ports:
      - "8083:8083"
