global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'rbk_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['rbk:8081']
  - job_name: 'temperature_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['darksky:8082']
  - job_name: 'prediction_micrometer'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 5s
    static_configs:
      - targets: ['prediction:8083']

